USE `produtos_jdbc`;

DROP TABLE IF EXISTS `PRODUTOS`; 

CREATE TABLE PRODUTOS(
    PRODUTOS_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(64),
    DESCRICAO VARCHAR(64),
    MARCA VARCHAR(64),
    CATEGORIA VARCHAR(64),
    PRECO VARCHAR(64),
    CUSTO VARCHAR(64)
);

INSERT INTO PRODUTOS (NOME, DESCRICAO, MARCA, CATEGORIA, PRECO, CUSTO)
VALUES ('Hollywoods Bleending', 'Album de Post Malone', 'Republic Record', 'Album', '500', '300');

INSERT INTO PRODUTOS (NOME, DESCRICAO, MARCA, CATEGORIA, PRECO, CUSTO)
VALUES ('Live in London', 'Album de Jorge e Mateus', 'Som Livre', 'Album', '500', '300');